server:
 port: 8764

spring:
 application:
  name: enurka-client

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
 instance:
  prefer-ip-address: true
  instance-id: ${spring.application.name}:${server.port}